### ISSUE TITLE
Wiki describing properties and algebraic objects

### ISSUE THREAD

**Issue by johnynek** [typelevel/algebra#11]
One of my hopes is that this project can introduce more programmers to the value of algebra in many domains. I don't expect them to have studied much math before, but I do expect them to be willing to read and learn new terms.

I think it would be nice to build a table of properties: (commutative, associative, idempotent, etc...), describe what they are, and then have a table, or a list of objects that satisfy them in some way. Generally we are speaking about binary operations here, but sometimes we talk about pairs of operations (e.g. distributive).

I think it would be valuable to have a page that sells some of the top most useful structures: (Semigroup enables parallelism, commutative enables reordering which enables parallelism in a different context, idempotent is highly useful in distributed systems, etc...)

**Comment by tixxit** [comment]
Looks like this is on the README now.
