### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by non** [typelevel/algebra#15]
I sort of threw together the README when this project was first starting.

I think we're starting to have a more concrete idea about the project, so ideally we could flesh this out a bit. Oscar's guide on how to merge PRs could be expanded into what we expect to include (or leave out) of the library, design philosophy, as well as a process for how to contribute (and more importantly, where and how to discuss potential contributions).

Also, I'd like to bring this project under the Typelevel Code of Conduct. Any objections?

**Comment by tixxit** [comment]
While the README has improved, this issue is open-ended enough that it can't ever really be closed - so closing now :)
