### ISSUE TITLE
Publishing, versioning

### ISSUE THREAD

**Issue by johnynek** [typelevel/algebra#18]
I was thinking it might be good to publish a series of releases (0.0.x) and make branches of algebird and spire that pull those jars. We might turn up some issues at that that point and want to make quick fixes.

I think when we have versions of 0.0.x that compile for both Spire and Algebird, we could publish 0.1.0 and then publish new versions of Algebird and Spire to use those.

Next, it would be great to use Mima to enforce no binary incompatibilities between x.y.z and x.y.z'. We struggled with binary incompatibility issues for a long time until we got more rigorous about such testing. Recently, on the x.y develop branches have mima running as part of the travis tests so we can introduce breaks when there should be minor improvements.

**Comment by sritchie** [comment]
Can we close this as well?
