### ISSUE TITLE
Upgrade to Cats RC1 

### ISSUE THREAD

**Issue by MansurAshraf** [typelevel/algebra#208]
Hello,

Algebra is bringing older version of cats in both Spire and Algebird. Can you please upgrade to cats RC1 and cut a new release?

Thanks

**Comment by johnynek** [comment]
#206 and #207 address this.

Also note this is a warning which will not hit a binary issue if you are not using the laws.

**Comment by ryan-williams** [comment]
Weird to close this when #207 hasn't been merged?

`org.typelevel:spire` has a transitive cats:0.9.0 dep because of this, and `fastOptJS` in a library that depends on spire fails with:

```scala
Referring to non-existent method cats.kernel.Order.on$mIcI$sp(scala.Function1)cats.kernel.Order
```
