### ISSUE TITLE
publish for Scala 2.13.0-M5

### ISSUE THREAD

**Issue by erikerlandson** [typelevel/algebra#219]
Dependency for https://github.com/non/spire/issues/742

**Comment by erikerlandson** [comment]
available for 2.13.0-M5: scalacheck-1.14.0, scalatest-3.0.6-SNAP3
missing cats, which in turn depends on https://github.com/typelevel/machinist/issues/31

**Comment by erikerlandson** [comment]
plugin dependency sbt-scalajs can be upgraded to 0.6.25, to get 2.13.0-M5

**Comment by johnynek** [comment]
I think scalacheck 1.14 is binary incompatible with 1.13.6 so I think this makes the laws package binary incompatible.

Which may be okay. I guess we can bump a version.

**Comment by erikerlandson** [comment]
I also don't see a huge problem with doing what scalatest did with "3.0.6-SNAPx", although presumably scala 2.13 is the future so moving in that direction on a non-snapshot release is good imo.

**Comment by ceedubs** [comment]
@johnynek Unfortunately I don't think that it's compatible (pre-Scala 2.12 at least). See https://github.com/typelevel/cats/issues/2449 (where you said the same). I'd love to find out otherwise though :\

**Comment by erikerlandson** [comment]
machinist-0.6.6 now available with 2.13.0-M5

**Comment by SethTisue** [comment]
note that @xuwei-k did some work in this direction at #217

**Comment by erikerlandson** [comment]
`cats` PR for 2.13.0-M5:  https://github.com/typelevel/cats/pull/2589

**Comment by erikerlandson** [comment]
`cats` 1.5.0-RC0
https://github.com/typelevel/cats/releases/tag/v1.5.0-RC0

**Comment by johnynek** [comment]
In idea I’ve had is replace the TraversableOnce methods with two methods of the same name. One on Iterator one on Iterable. The Iterable one by default can call the other.

Working with Iterator is pretty critical in big data systems that don’t always allow you to iterate twice.

What do you think?

**Comment by erikerlandson** [comment]
@johnynek that seems totally sane to me - the only case that seems ambiguous there is Stream, which is being replaced(?) by LazyList in 2.13. Stream/LazyList are (iiuc) neither Iterator nor Iterable.

**Comment by erikerlandson** [comment]
btw I was _not_ planning on fixing TraversableOnce related issures.
unless nobody else wants to :)

**Comment by SethTisue** [comment]
`Stream` and `LazyList` are both `Iterable`s

**Comment by johnynek** [comment]
@erikerlandson I don’t think anyone is working on it, thanks.

I’m pretty skeptical the 2.13 churn is going to be a net positive. Twitter (and Stripe) are not even on 2.12 yet. I can’t imagine how long 2.13 will take.

**Comment by johnynek** [comment]
I’m really trying hard not to rant about how much work it is to keep sbt up to date and have publishing working reliably...

**Comment by erikerlandson** [comment]
@SethTisue this is a bit tangent, but the [scaladoc](https://www.scala-lang.org/files/archive/api/2.13.x/scala/collection/immutable/LazyList$.html) list of super-types does not indicate anything about being a subclass of `Iterable` (however the code does).

**Comment by erikerlandson** [comment]
I finally figured it out - the page I had was the companion object page, not the class page :/

**Comment by SethTisue** [comment]
what's next here? (just curious, just checking)

**Comment by erikerlandson** [comment]
If #221 is approved, that should be sufficient for a release built against 2.13, but @johnynek would know more about other release roadmap concerns.

**Comment by larsrh** [comment]
#223

**Comment by larsrh** [comment]
Done.

**Comment by SethTisue** [comment]
scala/make-release-notes@261159060de4fd224c52c048d70ee5991cef90e7
