### ISSUE TITLE
support optional by-name RHS parameters 

### ISSUE THREAD

**Issue by non** [typelevel/algebra#25]
We had talked about having a variant of `combine` which was by-name in the right-hand side parameter. By default it would dispatch to the strict `combine` but this would allow other implementors to override this and change the behavior.

**Comment by johnynek** [comment]
This sounds fine to me. This could align better with Scalaz's notion of a Monoid, right?

Of course, you could get something like now this with:
```scala
def combineLazy(a: T, b: => T): T = combineAll(Stream.cons(a, Stream(b)))
```

**Comment by non** [comment]
Right, exactly.

In fact, a good ScalaCheck property would be ensuring that `combineLazy(a, b) ?== combineAll(a #:: b #:: Stream.empty`.

**Comment by johnynek** [comment]
What about left vs right by-name? Why would we prefer one over the other? What are some examples where we will want this?

**Comment by non** [comment]
Well, the design was initially intended to support Scalaz's `Semigroup[A]` definition -- I was deferring to their design. The two uses I know of which benefit from this definition are:

 * Short-circuiting operations (e.g. `Semigroup[Boolean]`). This seems pretty marginal.
 * Supporting lazy append/concat for streams, collections, etc.

I think the design they use comes from Haskell (although there both parameters are call-by-need I think). I suppose we could provide a method that was by-name for both parameters and let users decide what to do.

Or we could drop this issue.

Maybe @larsrh, @copumpkin, or someone else could chime in about the possible benefits of lazy variants of `combine`?

**Comment by johnynek** [comment]
If `Semigroup[Boolean]` is the only thing we can find (aside the trivial examples a + b = a or a + b = b), I'm pretty uninclined to do this.

I assume that scalaz did this as a matter of course because they want to emulate Haskell in this regard. I might mention: Idris does not do that by default and isn't that even more smarty pants than Haskell? ;)

In all seriousness, can't you emulate this now:
```scala
trait Lazy[+T] {
  def get: T
}
object Lazy {
  implicit def from[T](t: => T): Lazy[T] = new Lazy[T] {
    lazy val get = t
  }
}

class LazyOr extends Semigroup[Lazy[Boolean]] {
  def combine(a: Lazy[Boolean], b: Lazy[Boolean]) = if (a.get) a else b
}
```

**Comment by non** [comment]
I agree that we probably need more than `Semigroup[Boolean]` which is why I was hoping to hear about some more interesting use cases.

**Comment by tixxit** [comment]
I think we're all pretty comfortable with the design we have now - users can bring their own laziness via types if they want.
