### ISSUE TITLE
Consider publishing under org.typelevel instead of org.spire

### ISSUE THREAD

**Issue by non** [typelevel/algebra#26]
This is mostly administrative, but given that we are trying to generalize Spire, publishing under `org.spire-math` might be a bit weird.

I don't think this issue would affect who has push access to the repo, or anything else, besides associating the project with Typelevel and changing the artifact ID.

What do you all think?

**Comment by johnynek** [comment]
Sounds fine to me. I can even see moving the project from non/ to typelevel/ at some point.
