### ISSUE TITLE
Add benchmarking project

### ISSUE THREAD

**Issue by non** [typelevel/algebra#31]
It would be good to have a benchmarking project defined. This would allow us to do a few things:
1. Get benchmarks for `std` instances.
2. Confirm that miniboxing/specialization is working correctly.
3. Avoid performance regressions for helper methods.

What do you all think? Spire has done this and it's been really useful over the years.

**Comment by johnynek** [comment]
+1 to this. Lots of choices we make are about perf. Without benchmarks we are flying blind.
