### ISSUE TITLE
Add a Mima test for core

### ISSUE THREAD

**Issue by johnynek** [typelevel/algebra#68]
discussed in #18. I think we should be SUPER conservative with algebra-core, which if we succeed with this, could be a dependency of spire, algebird, and transitively scalding and summingbird (perhaps spark would use it if we can gain traction as a stable abstraction for algebraic concepts).

With mima, we could make sure we fail the build if there is any binary compatibility issue with changeds to algebra-core.

We can probably be a bit more free with algebra-std assuming that is less often a direct dependency.

**Comment by non** [comment]
Sounds good to me. Things are feeling relatively stable, I just opened one issue on core but otherwise I'm pretty satisfied.

**Comment by sritchie** [comment]
This is done. Can we close @johnynek?

**Comment by johnynek** [comment]
Yeah, we can. We just need to fix the mima issue, which should be fixable.

**Comment by sritchie** [comment]
Fixed in my PR now
